version: "3.9"
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
  dockub:
    image: erthill/dockub
    depends_on: 
      - mssql
    container_name: dockub
    ports:
      - 5000:80